apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: hello
          image: harbor.sysco-pcf.sysco.corby.cc/sof/hello:latest

