apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hello
  namespace: demo-project
spec:
  virtualhost:
    fqdn: hello-dev.contour.sysco-pcf.sysco.corby.cc
  routes:
    - services:
        - name: hello
          port: 8080


