apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httpproxy.yaml
configMapGenerator:
  - name: hello
    literals:
      - web.color=DarkSlateGray
images:
  - name: hello
    newName: harbor-lab.pks.corby.cc/development/hello